config/routes.rb
RailsForProposal::Application.routes.draw do
  
  match '/login' => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'
  
  resources :user_sessions

  resources :rates

  resources :sections

  resources :users do
     resources :section_roles
  end

  resources :requests do
    resources :section_roles
    resources :request_sections do
      resources :section_items
    end
  end

  root :to => "requests#index"

end

app/models/request_section.rb
class RequestSection < ActiveRecord::Base
  attr_accessible :section_id, :request_id, :comment
  
  belongs_to :request
  belongs_to :section
  has_many :section_roles, :dependent => :destroy
  has_many :section_items, :dependent => :destroy
  
  def update_average
    sum = 0.0
    for role in self.section_roles.not_pending
      sum += role.average
    end
    self.average = sum / self.section_roles.not_pending.count
    self.save
    self.request.update_average
  end
  
  def finished
    self.section_roles.pending.empty?
  end
  
end

app/controllers/request_sections_controller.rb
class RequestSectionsController < ApplicationController
  before_filter :logged_in?
  
  def index
    @request_sections = rfp.request_sections
  end

  def show
    rfp
    @request_section = RequestSection.find(params[:id])
  end

  def new
    @request_section = rfp.request_sections.build
  end

  def create
    @request_section = RequestSection.new(params[:request_section])
    if @request_section.save
      redirect_to @request_section.request, :notice => "Seccion creada exitosamente."
    else
      render :action => 'new'
    end
  end

  def edit
    @request_section = RequestSection.find(params[:id])
  end

  def update
    @request_section = RequestSection.find(params[:id])
    if @request_section.update_attributes(params[:request_section])
      redirect_to @request_section, :notice  => "Seccion actualizada exitosamente."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @request_section = RequestSection.find(params[:id])
    @request_section.destroy
    redirect_to request_sections_url, :notice => "Seccion eliminada exitosamente."
  end
  
  private
  def rfp
    @request = Request.find(params[:request_id])
  end
end

app/helpers/request_sections_helper.rb
module RequestSectionsHelper
end

app/views/request_sections/_form.html.erb
<%= semantic_form_for [@request, @request_section] do |form| %>
	<%= form.inputs do %>
	  <%= form.input :request_id, :as => :hidden %>
		<%= form.input :section, :label => t(:section) %>
	<% end -%>
	<%= form.buttons do  %>
		<%= form.commit_button :label => "Agregar Seccion" %>
	<% end %>

<% end -%>

app/views/request_sections/edit.html.erb
<% title "Editar secciones" %>

<%= render 'form' %>

<p>
  <%= link_to "Detalles", @request_section %> |
  <%= link_to "Ver todas", request_sections_path %>
</p>

app/views/request_sections/index.html.erb
<% title "Secciones" %>

<table>
  <tr>
    <th>Seccion</th>
    <th>RFP</th>
    <th>Comentario</th>
  </tr>
  <% for request_section in @request_sections %>
    <tr>
      <td><%= request_section.section_id %></td>
      <td><%= request_section.request_id %></td>
      <td><%= request_section.comment %></td>
      <td><%= link_to "Detalles", request_section %></td>
      <td><%= link_to "Editar", edit_request_section_path(request_section) %></td>
      <td><%= link_to "Eliminar", request_section, :confirm => '¿Está seguro?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Crear nueva seccion", new_request_request_section_path %></p>

app/views/request_sections/new.html.erb
<% title "Agregar Secciones" %>

<%= render 'form' %>

<p><%= link_to "Crear nueva sección", sections_path%></p>

<p><%= link_to "Volver", requests_path %></p>

app/views/request_sections/show.html.erb
<% title "Seccion" %>

<strong><%= @request_section.request.name %></strong>
(<em><%= @request_section.section.name %></em>)
<ul>
  <% for item in @request_section.section_items %>
    <li><%= item.name %></li>
  <% end -%>
</ul>

<%= link_to "Agregar item", new_request_request_section_section_item_path(@request, @request_section) %>