config/routes.rb
RailsForProposal::Application.routes.draw do
  
  match '/login' => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'
  
  resources :user_sessions

  resources :rates

  resources :sections

  resources :users do
     resources :section_roles
  end

  resources :requests do
    resources :section_roles
    resources :request_sections do
      resources :section_items
    end
  end

  root :to => "requests#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  
  attr_accessible :first_name, :last_name, :username, :email, :password, :password_confirmation, :admin

  validates :username, :uniqueness => true

  has_many :section_roles, :dependent => :destroy
  
  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :logged_in?
  before_filter :is_admin?, :only => [:index, :new, :create, :destroy]
  before_filter :is_current_user?, :only => [:show, :edit]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Usuario creado exitosamente."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice  => "Datos actualizados exitosamente."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, :notice => "Usuario eliminado exitosamente."
  end
  
  private
  def is_current_user?
    redirect_to(root_url, :notice => "No esta autoraizado para ver este recurso") unless current_user == User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label t(:first_name) %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label t(:last_name) %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label t(:username)%><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label t(:password) %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label t(:password_confirmation) %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label t(:email) %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label t(:admin) %>
    <%= f.check_box :admin %>
  </p>
  <p><%= f.submit t(:create) %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Editar Usuario" %>

<%= render 'form' %>

<p>
  <%= link_to "Perfil", @user %> |
  <%= link_to "Ver todos", users_path %>
</p>

app/views/users/index.html.erb
<% title "Usuarios" %>

<table>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Nombre de usuario</th>
    <th>E-mail</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= link_to "Perfil", user %></td>
      <td><%= link_to "Editar", edit_user_path(user) %></td>
      <td><%= link_to "Eliminar", user, :confirm => '¿Está seguro?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Registrar usuario", new_user_path %></p>

app/views/users/new.html.erb
<% title "Nuevo Usuario" %>

<%= render 'form' %>

<p><%= link_to "Ver todos", users_path %></p>

app/views/users/show.html.erb
<% title "Usuario" %>

<div id="user-info">
  <p>
    <strong>Nombre:</strong>
    <%= @user.first_name %>
  </p>
  <p>
    <strong>Apellido:</strong>
    <%= @user.last_name %>
  </p>
  <p>
    <strong>Nombre de usuario:</strong>
    <%= @user.username %>
  </p>
  <p>
    <strong>E-mail:</strong>
    <%= @user.email %>
  </p>

</div>

<div id="user-section-roles">
  <h2>Roles pendientes</h2>
  <ul>
    <% for section_role in @user.section_roles.pending %>
      <li>
        <%= section_role.request_section.request.name %>(<em><%= section_role.request_section.section.name %></em>)
        <%= link_to "Calificar", new_rate_path(:id => section_role.id) %>
      </li>
    <% end -%>
    <%= link_to "Ver todos", user_section_roles_path(@user) %>
  </ul>
</div>

<p>
  <%= link_to "Editar datos", edit_user_path(@user) %> |
  <%= link_to "Eliminar", @user, :confirm => '¿Está seguro?', :method => :delete %> |
  <%= link_to "Ver todos", users_path %>
</p>