config/routes.rb
RailsForProposal::Application.routes.draw do
  
  match '/login' => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'
  
  resources :user_sessions

  resources :rates

  resources :sections

  resources :users do
     resources :section_roles
  end

  resources :requests do
    resources :section_roles
    resources :request_sections do
      resources :section_items
    end
  end

  root :to => "requests#index"

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :name, :start_date, :decision_date, :company, :comment, :filename, :response_time, :status, :average, :file_upload
  
  attr_accessor :file_upload

  validates :name, :uniqueness => true

  has_many :request_sections, :dependent => :destroy
  has_many :sections, :through => :request_sections
  has_many :section_roles, :through => :request_sections
  
  before_save :save_file
  
  def rated
    self.status != 'pending'
  end
  
  def section(id)
    self.request_sections.find_by_section_id(id)
  end
  
  def users    
    User.where(:id => self.section_roles.inject([]){ |a, s| a << s.user_id } )
  end
  
  def save_file
    return unless self.file_upload
    self.filename = self.file_upload.original_filename
    directory = "public/upload/rfp"
    path = File.join(directory, self.filename)
    File.open(path, "wb") { |f| f.write(self.file_upload.read) }
  end
  
  def update_average
    sum = 0.0
    for section in self.request_sections
      sum += section.average if section.average > 0.0 
    end    
    self.average = sum / self.request_sections.count
    save
  end
  
  def finished
    self.request_sections.inject(true){ |res, sec| res &&= sec.finished }
  end
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  before_filter :logged_in?, :except => [:index]
  before_filter :is_admin?, :only => [:new, :edit, :create, :destroy] 
  
  def index
    @requests = Request.all
  end

  def show
    @request = Request.find(params[:id])
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(params[:request])
    if @request.save
      redirect_to @request, :notice => "RFP creado exitosamente."
    else
      render :action => 'new'
    end
  end

  def edit
    @request = Request.find(params[:id])
  end

  def update
    @request = Request.find(params[:id])
    if @request.update_attributes(params[:request])
      redirect_to @request, :notice  => "RFP actualizado exitosamente."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to requests_url, :notice => "RFP eliminado exitosamente."
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for @request, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label t(:name) %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label t(:start_date) %><br />
    <%= f.date_select :start_date %>
  </p>
  <p>
    <%= f.label t(:decision_date) %><br />
    <%= f.date_select :decision_date %>
  </p>
  <p>
    <%= f.label t(:company) %><br />
    <%= f.text_field :company %>
  </p>
  <p>
    <%= f.label t(:file) %><br />
    <%= f.file_field :file_upload %>
  </p>
  <p><%= f.submit t(:register) %></p>
<% end %>

app/views/requests/edit.html.erb
<% title "Editar RFP" %>

<%= render 'form' %>

<p>
  <%= link_to "Administrar", @request %> |
  <%= link_to "Ver todos", requests_path %>
</p>

app/views/requests/index.html.erb
<% title "RFP's" %>

<table>
  <tr>
    <th><%= t(:name) %></th>
    <th><%= t(:start_date) %></th>
    <th><%= t(:decision_date) %></th>
    <th><%= t(:company) %></th>
    <th><%= t(:status) %></th>
    <th><%= t(:score) %></th>
    <th><%= t(:comment) %></th>
  </tr>
  <% for request in @requests %>
    <tr>
      <td><%= request.name %></td>
      <td><%= request.start_date %></td>
      <td><%= request.decision_date %></td>
      <td><%= request.company %></td>
      <td><%= t(request.status) %></td>
      <td><%= "%0.2f" % request.average %></td>
      <td><%= request.comment %></td>
      <td><%= link_to "Administrar", request %></td>
      <td><%= link_to "Ver", "/upload/rfp/#{request.filename}" %></td>
      <td><%= link_to "Editar", edit_request_path(request) %></td>
      <td><%= link_to "Eliminar", request, :confirm => '¿Está seguro?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Registrar RFP", new_request_path %></p>
<p><%= link_to "Registrar usuario", new_user_path %></p>

app/views/requests/new.html.erb
<% title "Nuevo RFP" %>

<%= render 'form' %>

<p><%= link_to "Ver todos", requests_path %></p>

app/views/requests/show.html.erb
<% title "RFP" %>


<div id="rfp-status">
  <div id="accept">
    <h2><%= t(:accepted) %></h2>
    <% for role in @request.section_roles.accepted %>
      <div class="user-accept">
        <div class="role-score">
          <strong><%= "%0.2f" % role.average %></strong>
        </div>
        <p><strong><%= role.user.full_name %></strong></p>
        <p><em><%= role.request_section.section.name %></em></p>
        <% if role.comment %>
          <blockquote>"<%= role.comment %>"</blockquote>
        <% end -%>
      </div>
    <% end -%>
  </div>
  <div id="reject">
    <h2><%= t(:rejected)%></h2>
    <% for role in @request.section_roles.rejected %>
      <div class="user-reject">
        <div class="role-score">
          <strong><%= "%0.2f" % role.average %></strong>
        </div>
        <p><strong><%= role.user.full_name %></strong></p>
        <p><em><%= role.request_section.section.name %></em></p>
        <% if role.comment %>
          <blockquote>"<%= role.comment %>"</blockquote>
          <% end -%>
      </div>
    <% end -%>
  </div>
  <div id="decision">
    <% if @request.rated %>
      <em>Este RFP ya fue calificado</em>
    <% elsif @request.finished %>  
      <em>Todos los responsables han calificado el RFP</em>
      <% if current_user.admin %>
        <%= semantic_form_for @request do |form| %>
          <%= form.inputs do %>
            <%= form.input :status, :label => "¿Acepta este RFP?", :as => :radio, :collection => {'Si' => 'accepted', 'No' => 'rejected'} %>
            <%= form.input :comment, :label => t(:comment), :input_html => {:rows => 8, :cols => 50} %>
            <% end -%>
            <%= form.buttons do %>
              <%= form.commit_button t(:send) %>
            <% end -%>            
          <% end -%>
        <% else -%>
          <br/><em>Debe esperar que un usuario administrador califique el RFP</em>
        <% end -%>
    <% else %>
      <em>Faltan responsables por calificar el RFP</em>
    <% end -%>
  </div>
</div>

<div id="general-info">
  <div id="rfp-info">
    <h2><%= @request.name %></h2>
    <ul>
      <li><strong><%= t(:status) %>: </strong><%= t(@request.status) %></li>
      <li><strong><%= t(:start_date) %>: </strong><%= @request.start_date %></li>
      <li><strong><%= t(:decision_date) %>: </strong><%= @request.decision_date %></li>
	  <li><strong><%= t(:time_remaining) %>: </strong><%= (@request.decision_date) - (Date.current) %> días</li>
      <li><strong><%= t(:score) %>: </strong><%= "%0.2f" % @request.average %></li>
    </ul>    
  </div>
  <div id="responsibles">
    <strong><%= t(:responsibles) %></strong>
    <ul>
      <% for section_role in @request.section_roles %>
        <li><%= section_role.user.full_name %>(<em><%= section_role.request_section.section.name %></em>)</li>
      <% end -%>
    </ul>
    <%= link_to t(:add_responsible), new_request_section_role_path(@request) %>
  </div>
  <div id="sections">
    <strong><%= t(:sections) %></strong>
    <ul>
      <% for request_section in @request.request_sections %>
        <li><%= request_section.section.name %>(<em><%= "%0.2f" % request_section.average %></em>)<%= link_to "Agregar items", request_request_section_path(@request, request_section) %></li>
      <% end -%>
    </ul>
    <%= link_to t(:add_section), new_request_request_section_path(@request) %>
  </div>
</div>

<p>
  <%= link_to t(:edit), edit_request_path(@request) %> |
  <%= link_to t(:remove), @request, :confirm => '¿Está seguro?', :method => :delete %> |
  <%= link_to t(:back), requests_path %>
</p>