config/routes.rb
RailsForProposal::Application.routes.draw do
  
  match '/login' => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy'
  
  resources :user_sessions

  resources :rates

  resources :sections

  resources :users do
     resources :section_roles
  end

  resources :requests do
    resources :section_roles
    resources :request_sections do
      resources :section_items
    end
  end

  root :to => "requests#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application", "formtastic" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    
    <div id="container">
      <div id="user-nav">
        <% if current_user %>        
          <%= link_to "Principal", user_path(current_user) %> |
          <%= link_to t(:rfp), requests_path %> | 
          <% if current_user.admin %>
            <%= link_to t(:users), users_path %> |
          <% end -%>
          <%= link_to "Logout", logout_path %>
        <% else %>
          <%= link_to "Login", login_path %>
        <% end -%>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>